logging.pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4.4line %clr(:){faint} %m%n%wEx"
logging.pattern.file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4.4line %clr(:){faint} %m%n%wEx"

mos.config:
  #开发环境
  host: http://localhost:9700
  secret-key: b-T3wXaUu5umA3vumqEIVA==
  open-id: 5
  bucket-name: default
cloud:
  backup-paths:
    - srcPath: "E:/test"
      desPath: "/resources"
      excludes: ["**/*.tmp"]
      includes: ["**/*"]
