mos.config:
  #开发环境
  host: http://localhost:9700
  secret-key: b-T3wXaUu5umA3vumqEIVA==
  open-id: 5
  bucket-name: default
cloud:
  backup-paths:
    - srcPath: "E:/test"
      desPath: "/resources"
      excludes: ["**/*.tmp"]
      includes: ["**/*"]